title: Durham Hackathon
description: A short intro to numerical simulation

show_downloads: false

theme: jekyll-theme-hacker

url: 'https://durham-hackathon.github.io/durham-hackathon'
baseurl: 'durham-hackathon/'
